export const APPOINTMENT_ACTION_TYPES = {
  SET_APPOINTMENT: "SET_APPOINTMENT",
  ADD_APPOINTMENT: "ADD_APPOINTMENT",
  DELETE_APPOINTMENT: "DELETE_APPOINTMENT",
  UPDATE_APPOINTMENT: "UPDATE_APPOINTMENT",
};
